ez_get_speakers:
    pattern: /speakers/list
    defaults:
        _controller: ez.controller.speakers:getList
    methods: [GET]

ez_get_talks:
    pattern: /talks/list
    defaults:
        _controller: ez.controller.talk:getList
    methods: [GET]