ez_get_speakers:
    pattern: /speakers/list
    defaults:
        _controller: ez.controller.speakers:getList
    methods: [GET]

ez_get_speaker:
    pattern: /speaker/{id}
    defaults:
        _controller: ez.controller.speaker:getSpeaker
    methods: [GET]

ez_get_talks:
    pattern: /talks/list
    defaults:
        _controller: ez.controller.talk:getList
    methods: [GET]

ez_get_talks_by_speaker:
    pattern: /talks/get/{speakerId}
    defaults:
        _controller: ez.controller.talk:getListBySpeaker
    methods: [GET]

