ez_get_speakers:
    pattern: /speakers/list
    defaults:
        _controller: ez.controller.speakers:getList
    methods: [GET]

ez_get_speaker:
    pattern: /speaker/{speakerId}
    defaults:
        _controller: ez.controller.speakers:getSpeaker
    methods: [GET]

ez_get_talks:
    pattern: /talks/list
    defaults:
        _controller: ez.controller.talks:getList
    methods: [GET]

ez_get_talk_by_id:
    pattern: /talk/{talkContentId}
    defaults:
        _controller: ez.controller.talks:getTalk
    methods: [GET]

ez_get_talks_by_speaker:
    pattern: /talks/get/{speakerId}
    defaults:
        _controller: ez.controller.talks:getListBySpeaker
    methods: [GET]

ez_get_sponsors:
    pattern: /sponsors/list
    defaults:
        _controller: ez.controller.sponsors:getList
    methods: [GET]