services:
    ez.controller.speakers:
        class: Ez\ConferenceRestBundle\Rest\Controller\SpeakersController
        parent: ezpublish_rest.controller.base

    ez.value_object_visitor.news:
        parent: ezpublish_rest.output.value_object_visitor.base
        class: Ez\ConferenceRestBundle\Rest\ValueObjectVisitor\Speakers
        arguments: [ @ezpublish_rest.field_type_serializer ]
        tags:
            - { name: ezpublish_rest.output.value_object_visitor, type: Ez\ConferenceRestBundle\Rest\Values\Speakers }
